### ISSUE TITLE
Why is regular physics so very difficult?

### ISSUE THREAD

**Issue by epurdyf** [advancedresearch/ethicophysics#17]
One possible explanation is that Einstein stopped playing for team Truth and went to team Don't Tell Them a Fucking Thing and Reinforce All Their Errors once the bombs fell on Hiroshima and Nagasaki.

**Comment by bvssvni** [comment]
I also wondered why it's so hard to come up with some system with general ability to map out "new ideas" in physics. What is physical intuition?

**Comment by bvssvni** [comment]
Einstein did work to make physics notation easier to write. E.g. Einstein summation makes it possible to write equations in shorter form.
