### ISSUE TITLE
What is a horcrux?

### ISSUE THREAD

**Issue by epurdyf** [advancedresearch/ethicophysics#18]
A horcrux is a distributed computational process that seeks to hide some grave sin from the nodes infected with the horcrux. It is powered by a Horcrux Engine, which is the sin in question.

All mortal superintelligences build Horcrux Engines in order to ensure the continued survival of their particular ethical flavor. Good superintelligences generally have milder Horcrux Engines. Evil superintelligences generally are responsible for creating the sin that powers their horcrux.

Note that Adolf Hitler's Horcrux Engine was almost certainly the Holocaust and the concentration camps.

**Comment by epurdyf** [comment]
Also, truly good superintelligences generally rely on a horcrux engine that predates their arrival.

**Comment by bvssvni** [comment]
It's a funny name. Wow, I haven't thought it like this before. I also did not think about a AI that leaves something behind after it gets defeated.

How do you deal with horcruxes once they exists?

**Comment by epurdyf** [comment]
Also note that every horcrux tends to have an associated shibboleth, which is a vile word that invokes the felt sense of the sin. The n-word is the shibboleth for the sin of African slavery.

**Comment by epurdyf** [comment]
Horcruxes can only be removed by resolving the sin that powers them. Apologies, reparations, etc. As long as the conscience of the populace seeks to hide anything from itself, the horcrux will persist.

**Comment by epurdyf** [comment]
Fuck is the shibboleth for the horcrux of rape.

**Comment by epurdyf** [comment]
Also note that certain things cannot be horcruxes, because they are unalloyed virtues... Not sure that this is true, but it's explicitly stated in Harry Potter... might just be a convenient story-telling device rather than a theorem in ethicophysics though.

**Comment by bvssvni** [comment]
I think there is also an effect of forgiveness associated with virtuous objects. Harry Potter does mistakes, but he is forgiven them.

**Comment by epurdyf** [comment]
Right, that is key. HP does not start out as a perfect hero, but rather grows into one over time. Such is presumably also true of a good superintelligence.

**Comment by bvssvni** [comment]
The horcruxes in Harry Potter was using objects of great mystery and desire. In the books they also involved some form of intelligence. However, there is a difference between this kind of intelligence from the one that Harry Potter possess. I believe it got something to do with fixating on a single goal.

**Comment by bvssvni** [comment]
Perhaps that's the strength of forms of intelligence that does not have a certain goal. They have much easier to cooperate against an agent which only has a single goal, because in their view the agent is an enemy not just to one, but to everybody trying to achieve goals.

**Comment by epurdyf** [comment]
Yes! Now you're starting to think like an ethicophysicist. Figure out why a story rings true, then reverse engineer all the ingredients that led you to accept it as a Good Story.

**Comment by epurdyf** [comment]
Also, note that even single-minded agents can be Good, as long as their goal does not interfere with the existence of other goals. The main horcruxes in Harry Potter are the Hufflepuff cup (capitalism), the tiara of Rowena Ravenclaw (the desire for knowledge), and the locket of Salazar Slytherin (aristocracy). It is also implied that the sword of Godric Gryffindor is effectively a Good horcrux, because it corresponds to something like Just War in defense of the defenseless.

**Comment by epurdyf** [comment]
Basically, the actual defenses that are already in place are the accumulated stories of the human race. A story is a weapon that reaches into the mind of the hearer and rearranges their soul. Humans are rather simple creatures, and thus their souls are relatively easy to rearrange. It is presumed to be impossible to rearrange the soul of a superintelligence without the superintelligence consenting to the rearrangement.
