### ISSUE TITLE
Is there a more accurate term for "free will"?

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/ethicophysics#29]
I suggest "self determination".

The concept of free will is a little ambiguous, because people mean different things. Some mean that people have souls that gives them some kind of supernatural power of matter. Other people mean that free will is something happens when things to according to the desires of a person to some extent. Those a very different interpretations.

I like the sounding of "self determination" because it puts things in perspective. It is not just about achieving a single task according to some desires, but about determining some greater part of the future by the will of making it happen. Free will means in this context that humans can change the a default predicted outcome from nobody changing their behavior to something that is caused by a change of behavior.

Of course, the future must happen according to physical laws, but since people are part of physical nature this means something happening according to somebody's will is because their will is part of physics.

**Comment by epurdyf** [comment]
Moral entropy is probably the closest term that makes sense.

**Comment by bvssvni** [comment]
Is the key idea to describe free will as some kind of field? Are you thinking about e.g. modelling this as a scalar field in spacetime?

**Comment by bvssvni** [comment]
Ah. So saying that it's predicted to be at somewhere at some point in the future is the same as saying whether there will be peace there (or no resistance). The aliens could say the same about our place. If we both measure it, then it's peace. If one side measures it, they won.

**Comment by epurdyf** [comment]
Yes, that is an excellent way of putting it. If we measure the Ethics of alien civilizations and find them acceptable, we can live in peace. If we do not find them acceptable, there will be war, and we may not win that war. Ultimately peace is smarter than a war that one may not win... but wars that are necessary are necessary.

**Comment by bvssvni** [comment]
It's interesting how this ties up with physics. For example, in very strong gravitational fields, such as close to a star, the value is very low because of the difficulty of achieving goals there.

Perhaps relevant https://en.wikipedia.org/wiki/Mean_field_game_theory

**Comment by epurdyf** [comment]
Yes, that is an excellent point! There's some Doctor Who episodes that sort of semi-intentionally explore that particular intersection of physics and ethics, because there's a human colony with a cyberman infestation orbiting a black hole. Highly recommended.

**Comment by epurdyf** [comment]
Mean field game theory is indeed relevant. But the mean field approximation is always just that, an approximation. Sometimes it is not a very good approximation.
