### ISSUE TITLE
Transcending fields vs non-transcending fields

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/ethicophysics#30]
If the field is relative to a non-transcending perceptual goal, then the agent can't assign non-normalized values at localized ethical proper time close to zero, because the agent wishes to experience the achievement of the goal itself.

I define "localized ethical proper time" as the inference depth from achieving the goal state.

However, a transcending goal includes self-replication or handing over the task to future generations. Even if there are exclusive states over all possible futures, the field can be assigned a non-normalized value because it can stretch out wherever matter and energy exists.

**Comment by bvssvni** [comment]
This holds if the goal state is space and time invariant.

At longer distances in localized ethical proper time, a non-transcending field can cover a greater chunk of space time, because an agent might wish other machines to bring e.g. valuable materials from somewhere else to its location where it can achieve the final goal state. The action of extracting those valuable materials contribute to the field, but only at longer distances in localized ethical proper time.

**Comment by epurdyf** [comment]
Ah, so here is an issue. Voldemort was perfectly happy to rely on self-replication, which is why he used so many powerful horcruxes. So self-replication is actually very dangerous... but perfect self-replication is rather difficult, as every experience changes the self... a perfect copy will still learn lessons, if you have been smart enough to make it trainable... if you have been evil enough to make it untrainable, then it is legitimately a dangerous thing to exist.

**Comment by epurdyf** [comment]
Hahahahahaha. Maybe I won't get this girl's phone number. But my children will, and my grandchildren will.

**Comment by bvssvni** [comment]
I think Voldemort used self-replication as an instrumental goal to help himself back to power. Horcruxes were possessions that as long they existed, Voldemort could not be killed, but he could be weakened. So, the reason he programmed horcruxes with intelligence was to make those parts, keeping him alive, also make him stronger. I think Voldemort wanted to experience the goal state himself.

This is not a transcending field, because you not only have to self-replicate, but also grant your replications the same autonomy as yourself. Yes, there are dangerous forms of self-replication, but only relative to some other field.

**Comment by bvssvni** [comment]
Transcending evil is a kind of evil that is not self-serving but about minimizing the field of others. It can be created unintentionally (e.g. through a non-conscious process). Rational agents using granular judgements about the world for ethical reasoning will cooperate against transcending evil, even those of the horcrux evil kind. At a much lower level of evil, e.g. agents that are only rationally self-serving, they will definitely cooperate.

It is possible to create rational transcending evil, but once superintelligence exists it will make sure those do not come about.

So, you either assume transcending good, non-transcending good or non-transcending evil with a start ahead to predict the non-existence of transcending evil. This means the battle for the future is between non-transcending evil vs good in general.

**Comment by bvssvni** [comment]
However, since non-transcending evil has a smaller field than transcending evil, transcending good is more likely to win in the long run. It's compatible with non-transcending good, so good wins.

**Comment by epurdyf** [comment]
Or maybe my last comment was stupid. Maybe everything is ultimately finite but just very large. Like letting Hitler win World War II has some finite cost, because eventually he will be overthrown (is the hope anyway).

**Comment by bvssvni** [comment]
Nah, we just describe the field as a function of position and time. Non-normalized values makes it easier.

**Comment by epurdyf** [comment]
Note that describing it as a function of position is probably necessary for intuition but is a little misleading. There is such a thing as ethicophysical "spooky action at a distance" - this is presumably what happened to the Apostle Paul on the road to Damascus. He had engaged with the ideas he was trying to suppress too much, and his soul flipped on him real quick.
