### ISSUE TITLE
The Anti-Psychotic Q-Learner Trick

### ISSUE THREAD

**Issue by epurdy** [advancedresearch/ethicophysics#32]
Have now dropped an initial experiment and a writeup. Anyone who is interested is welcome to discuss the implications her, or to submit pull requests to extend the experiments and/or paper.

**Comment by bvssvni** [comment]
Interesting and brilliant. I think this work can be used to show that arbitrary weakening of neutral judgements is possible.

It makes me think about a strategy for achieving safe super-intelligence: Put the AI on the neutral side and later port it piece by piece to the PZR side. First, restrict the range severely while it's a borgie. When it reaches maturity, weaken the range and repeat training. Finally, when the range is wide enough to approximate PZR, form a guarded utility function that trains up another borgie for another domain within a severely restricted range. Repeat the procedure and develop the PZR side from mature borgs.

**Comment by epurdy** [comment]
Thanks! :)

I agree with your prescription of developing the PZR from mature borgs. It's going to be kind of stressful to watch, though. Or at least I imagine so.

**Comment by epurdy** [comment]
(PZR side)

**Comment by bvssvni** [comment]
I ran the experiment and got a slightly different image:

![borgies](https://user-images.githubusercontent.com/1743862/39970724-b0c0bd90-56f0-11e8-8723-a31f94713b58.png)

Is there something wrong with the red and the purple line?

**Comment by epurdy** [comment]
Oh noooooo. I must have messed it up somehow when I was commenting it for clarity. I think it's no longer danger aware... Need to figure out what I messed up.

**Comment by epurdy** [comment]
I think it's intentionally making mistakes to keep its cumulative reward near 0?

**Comment by epurdy** [comment]
Did you edit the file at all? Want to make sure it's my fault before diving in seriously...

**Comment by epurdy** [comment]
Did you by any chance take out the fear term in the action choice? Would have the effect observed.

**Comment by epurdy** [comment]
Reran it and got a different graph with the same qualitative properties as the one in the PDF. So I think you must have edited it in some way that made it no longer danger-aware. Would be good to document what you did and add it to the .tex file as an ablation analysis.

![borgies_recalc](https://user-images.githubusercontent.com/923672/39971022-4b34ef42-56a9-11e8-9103-c9d32e9d7498.png)

**Comment by epurdy** [comment]
![borgies_nofear](https://user-images.githubusercontent.com/923672/39971268-02e07ca8-56ad-11e8-99dc-070b66bd131c.png)

Hm, here's the result of removing the fear term. Still not the same as what you got...

**Comment by bvssvni** [comment]
I reran and got same error as before. Perhaps it's a bug in some python package. I'll upgrade and run again.

**Comment by epurdy** [comment]
Well that's concerning, if the algorithm is so brittle that a different version of numpy or whatever changes the results. Doing a shitload of ablation analysis now.

**Comment by bvssvni** [comment]
For a while I got a different image, but when the program finished I got the same error. I'll rerun and see if I can get that different image again.

**Comment by epurdy** [comment]
Try updating matplotlib? Might just be a display problem rather than a correctness issue?

**Comment by epurdy** [comment]
Or use a different matplotlib backend so that you can manipulate the graph and zoom out in the y direction

**Comment by bvssvni** [comment]
Probably something wrong with my setup.

**Comment by epurdy** [comment]
Added ablation analysis, since your different results made me extremely paranoid about the legitimacy of my results. Still have no idea what's up with your setup.
