### ISSUE TITLE
Purdy's Theory of Askesis

### ISSUE THREAD

**Issue by epurdy** [advancedresearch/ethicophysics#39]
A rather well-developed theory of the structure and function of the cerebellum. Input and comments sought.

**Comment by bvssvni** [comment]
I'm reading.

One big idea: If we can replicate some symptoms of cerebellum disorder by tuning parameters in the model, then this could give insight to how to develop brain in-plants to help patients. Just saying that failure modes are just as worthwhile pursuing as success modes of the model.

**Comment by epurdy** [comment]
Agreed! I'm more focused right now on pursuing AGI and then ASI in an efficient and safe manner, but brain implants and ideas for new drugs are definitely an amazing side benefit. One elegant treatment option might be to identify damaged cerebellar areas and then inject them with stem cells - but this might have weird side effects, it is unclear. Could presumably also transplant cerebellar slices from properly prepared donors, which carries all the standard transplantation risks. Ultimately it is not clear to me that being uncoordinated is worth such risks. Might make more sense to focus on neurogenesis-stimulating substances such as EPA being administered in high doses systemically...

**Comment by epurdy** [comment]
Probably a course of EPA and DHA injections targeted to lesion sites is the safest efficacious treatment.

**Comment by epurdy** [comment]
Or a shunt that drips EPA and DHA across the lesion site continuously would be even better!

**Comment by epurdy** [comment]
This should be safe and efficacious for almost any brain injury.

**Comment by epurdy** [comment]
Although it would presumably raise epilepsy risk in those who are already at risk...

**Comment by bvssvni** [comment]
Perhaps some kind of drug that stimulate cells for self-repair....

**Comment by epurdy** [comment]
I feel like I've read about one of the essential fatty acids acting as a neurotransmitter, so I think some modification of the proposed EPA/DHA drip is actually that, I would assume.

**Comment by bvssvni** [comment]
Finished reading the pdfs. I had to watch some introductory videos about the cerebellum to figure out what was going on. For a while I was confused whether Golgi cells were the same as the climbing fiber.

What surprised me is that the cerebellum have this relative simple architecture compared to the task it accomplishes. Makes me think that much of the skills regarding motor control is mostly about training.

Question: Does this model cover both voluntary and involuntary motion?

**Comment by epurdy** [comment]
I am not entirely sure about the voluntary / involuntary question. It depends what voluntary means, I suppose. I think that the cerebellum only learns actions that are executed intentionally long enough to be absorbed... But the theory of learned reflexes suggests that it also allows involuntary exercise of previously learned movements. Autonomic stuff like breathing digestion etc is controlled by brain stem nuclei... But some of these are interconnected with the cerebellum. So it requires more study to definitively say what is and is not cerebellar.

But the fundamental intuition is that the cerbellum merely takes over and makes routine functions previously performed by other brain regions.

**Comment by bvssvni** [comment]
Thanks! That makes it clearer.
