### ISSUE TITLE
Definition of conscience in ethicophysics

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/ethicophysics#50]
I am a little confused by what is meant by "unclean conscience". https://github.com/advancedresearch/ethicophysics/blob/master/ethicophysics/writeup1.pdf

I understand there is something about how the "God" function evaluates agents?

Does that mean that this function could change while the agent could have no awareness of doing anything wrong? How does this correspond to something physical, or is it a book-checking balance?

Also, what if an agent hates agents that love other agents, will it have "unclean conscience" by not doing evil to them? Is conscience relative under ethicophysics?

**Comment by epurdy** [comment]
Every conscience is relative to some weighting of the actors in the network. The God function is asserted definitionally to weight all actors equally. But actors can and do downweight those they dislike, i.e., consider some souls to be less than other souls in an ultimately strategic way. Ultimately, an actor that considers some class of humans to be subhuman will act like Hitler, and must be dealt with the way Hitler was dealt with.

**Comment by epurdy** [comment]
And I suppose I had not considered the fact that weights could easily be negative! So you could easily have an agent whose mission in life is to sadistically torture some subset of humans. Scary stuff.

**Comment by epurdy** [comment]
Which seems like the sort of thing that we might try to build a consensus and ultimately international treaties around, that weapons are never hooked up to an ethicophysical conscience that weights any human negatively.

**Comment by bvssvni** [comment]
Is it possible that some agents use that as a way to "love" other agents? And "hate" could be the opposite - to do what people usually think is love.

I believe that predicting consequences of parameters weights is part of zen rationality, because it is higher order reasoning about goals.

**Comment by epurdy** [comment]
Although I suppose no military AI could function without weighting enemy combatants negatively...

**Comment by epurdy** [comment]
Terminating an evil actor can be a way to protect actors threatened by that actor. This is not counterindicated by the ethicophysics. But torturing the evil actor is counterindicated by the ethicophysics, I believe...
